language: python
sudo: required
python:
      - "2.7"
install:
      - sudo apt-get update
      - sudo apt-get -y install python python-pip
      - python -m pip install pymongo
      - python -m pip install couchdb
script:
      - python couch/setup.py
      - python couch/register.py
      - python couch/programCourses.py
notifications:
      email: false
